title: Secure Snippets
description: A collection of before/after code examples for building more secure software. 
theme: just-the-docs

url: http://secure-snippets.miladified.me

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
